### ISSUE TITLE
Plugin doesn't work on Paper 1.21.4 - Hard Fork

### ISSUE THREAD

**Issue by SequaciousGAMES** [cobrex1/TownyMenu#26]
**Describe the bug**
Plugin loads but fails to function on Paper 1.21.4

**Error**
```
[10:03:55 ERROR]: TownyMenu 1.8.10 encountered a [NoClassDefFoundError](http://www.google.com/search?hl=en&q=allinurl%3Adocs.oracle.com+javase+docs+api+noclassdeffounderror)! Please check your error.log and report this issue with the information in that file. Running [Paper](http://www.google.com/search?hl=en&q=allinurl%3Adocs.oracle.com+javase+docs+api+paper) 1.21.4-R0.1-SNAPSHOT and Java 21.0.2
[10:03:55 INFO]: java.lang.[NoClassDefFoundError](http://www.google.com/search?hl=en&q=allinurl%3Adocs.oracle.com+javase+docs+api+noclassdeffounderror): Could not initialize class me.cobrex.townymenu.join.JoinTownMenu
[10:03:55 INFO]:      at TownyMenu-[1.8.10].jar//me.cobrex.townymenu.town.command.TownMenuCommand.onCommand(TownMenuCommand.java:41)
[10:03:55 INFO]:      at TownyMenu-[1.8.10].jar//me.cobrex.TownyMenu.lib.fo.command.SimpleCommand.execute(SimpleCommand.java:406)
[10:03:55 INFO]:      at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:82)
[10:03:55 INFO]:      at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
[10:03:55 INFO]: java.lang.[ExceptionInInitializerError](http://www.google.com/search?hl=en&q=allinurl%3Adocs.oracle.com+javase+docs+api+exceptionininitializererror): [Exception](http://www.google.com/search?hl=en&q=allinurl%3Adocs.oracle.com+javase+docs+api+exception) java.lang.[ExceptionInInitializerError](http://www.google.com/search?hl=en&q=allinurl%3Adocs.oracle.com+javase+docs+api+exceptionininitializererror) [in thread "Server thread"]
[10:03:55 INFO]:      at TownyMenu-[1.8.10].jar//me.cobrex.townymenu.town.command.TownMenuCommand.onCommand(TownMenuCommand.java:41)
[10:03:55 INFO]:      at TownyMenu-[1.8.10].jar//me.cobrex.TownyMenu.lib.fo.command.SimpleCommand.execute(SimpleCommand.java:406)
[10:03:55 INFO]:      at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165)
[10:03:55 INFO]:      at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:1114)
[10:03:55 INFO]: [TownyMenu] !-----------------------------------------------------!
[10:03:55 INFO]: [TownyMenu]  Failed to execute command /townmenu
[10:03:55 INFO]: [TownyMenu] !-----------------------------------------------------!
```

**Plugin Version:**
1.8.10

**Server Jar and Version:**
Paper 1.21.4 - 65

**Comment by cobrex1** [comment]
Thanks for the report. I am aware the plugin is not working. I have a dev building working on paper 1.21.4v14, but not for the hard fork versions. I am working to get the error fixed.
